//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stationers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Stationary
    {
        public Stationary()
        {
            //this.Variants = new HashSet<Variant>();
        }

        public int Stationary_ID { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Category { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Name { get; set; }

        [StringLength(1500, MinimumLength = 3)]
        public string Image { get; set; }
        public string ForSubject { get; set; }

        [Range(0, 1000)]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Price { get; set; }

        [StringLength(500000)]
        public string Description { get; set; }

        public bool Favorite { get; set; }

        public Variant newVariant { get; set; }

        public static SelectList SubjectList { get; set; }
        public int Amount { get; set; }


        public virtual List<Variant> Variants { get; set; }
    }

}